### ISSUE TITLE
command gets cut off with ninja

### ISSUE THREAD

**Issue by John-Colvin** [atilaneves/reggae#194]
I have a rule like this:

`enum sdfmt = Target("SDC/bin/sdfmt", "make -C SDC bin/sdfmt DMD=" ~ options.dCompiler);`

which shows up in `compile_commands.json` as

```
    {
        "directory": "/Users/john/Git/Felix",
        "command": "make -C SDC bin/sdfmt DMD=/Users/john/dlang/ldc-1.33.0-beta2/bin/ldmd2",
        "file": ""
    }
```

but in `build.ninja` it's just this:

```
build SDC/bin/sdfmt: make 
```

which doesn't do what I want, obviously.

It works fine with the `make` backend, where I see the same thing in `compile_commands.json` but the following rule in the makefile:

```
SDC/bin/sdfmt:  Makefile
	@echo [make] Building SDC/bin/sdfmt
	make -C SDC bin/sdfmt DMD=$(DC)
```

(also, what is going on with it magically using `$(DC)` there?)

**Comment by atilaneves** [comment]
Ninja wasn't meant to be used with custom random user shell commands, but with pre-defined ones such as "compile", "link", etc. Reggae tries to be smart and make such shell commands usable by writing a "rule" (ninja parlance) for the command in question. That only works if the shell command includes `$in`, `$out`, or both. The rule in the example should have used `$out` for it to work, but I confess I don't know how that would work because the path is slightly different. An option is phony. I guess `cd SDC && make $out DMD=...`.

In any case, it wouldn't be expected that the command would be anything other than `make`: that would have been the rule ninja would write out. The rest ("-C SDC", etc.) would've been parameters.
